version: '2'

networks:
  cluster:
    driver: bridge
services:
  cassandra-node1:
    image: bitnami/cassandra:latest
    container_name: cassandranodeone
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    networks:
      - cluster

volumes:
  cassandra_data:
    driver: local
